version: '3'
services:
  rosmaster:
    image: alpineros/alpine-ros:melodic-ros-core
    container_name: rosmaster
    networks:
      - rosnet
    command: roscore
    ports:
      - "80:11311"

  rosgui:
    build:
      context: ./
      target: rosvnc_base
    container_name: rosgui
    ports:
      - 6080:80
    networks:
      rosnet:
        ipv4_address: 172.20.0.20
    environment:
      - ROS_HOSTNAME=172.20.0.20
      - ROS_MASTER_URI=http://rosmaster:11311
      - ROS_IP=172.20.0.20
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - rosmaster

networks:
  rosnet:
    name: rosnet
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.20.0.0/16
